/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.mysql.cj.protocol.Resultset;
import controller.ConectarDao;
import controller.Petdao;
import controller.Usuariodao;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Acesso;
import model.Animal;
import model.User;

/**
 *
 * @author veman
 */
public class TelaInicioUSER extends javax.swing.JFrame {

    private static int id_user;

    /**
     * Creates new form Login
     */
    public TelaInicioUSER(int userId) {
        id_user = userId;
        initComponents();
        ListarValores();
        //restaurarDadosComboBoxAcesso();
        ListarValoresPet();
        ListarValoresPetEncontrados();
        ListarValoresPetPerdidos();
        restaurarDadosComboBoxSituacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarPet1 = new javax.swing.JButton();
        PanelMenus = new javax.swing.JPanel();
        LabelMenu = new javax.swing.JLabel();
        MenuPerdidos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MenuAchados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        MenuCadastros = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        MenuUsers = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        MenuCadastrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LabelSair = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        PanelPerdidos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescriçãoPerdidos = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAnimaisPerdidos = new javax.swing.JTable();
        PanelAchados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAnimaisAchados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtDescriçãoAchados = new javax.swing.JTextArea();
        PanelCadastros = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableCadastros = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnEditarPet = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDescriçãoCadastros = new javax.swing.JTextArea();
        PanelPerfil = new javax.swing.JPanel();
        PanelEditarUser1 = new javax.swing.JPanel();
        txtEditNome1 = new javax.swing.JTextField();
        LabelNomeUser1 = new javax.swing.JLabel();
        textEditTel1 = new javax.swing.JTextField();
        LabelTelefoneUser3 = new javax.swing.JLabel();
        textEditEmail1 = new javax.swing.JTextField();
        LabelEmailUser3 = new javax.swing.JLabel();
        BtnSalvarEditUser1 = new javax.swing.JButton();
        txtEditId1 = new javax.swing.JTextField();
        LabelNomeUser8 = new javax.swing.JLabel();
        LabelTelefoneUser4 = new javax.swing.JLabel();
        textEditPass = new javax.swing.JTextField();
        PanelCadastrar = new javax.swing.JPanel();
        LabelTelefoneUser1 = new javax.swing.JLabel();
        TxtCadPetEspecie = new javax.swing.JTextField();
        LabelEmailUser1 = new javax.swing.JLabel();
        TxtCadPetRaca = new javax.swing.JTextField();
        LabelSenhaUser1 = new javax.swing.JLabel();
        TxtCadPetCor = new javax.swing.JTextField();
        BtnSalvarCadastroPet = new javax.swing.JButton();
        LabelNomeUser2 = new javax.swing.JLabel();
        LabelSenhaUser2 = new javax.swing.JLabel();
        cbxSituacao = new javax.swing.JComboBox<>();
        LabelNomeUser6 = new javax.swing.JLabel();
        TxtCadPetNome = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        TxtCadPetDetalhes = new javax.swing.JTextArea();
        PanelEditarPet = new javax.swing.JPanel();
        LabelNomeUser4 = new javax.swing.JLabel();
        textEditPetNome = new javax.swing.JTextField();
        LabelTelefoneUser2 = new javax.swing.JLabel();
        textEditPetEspecie = new javax.swing.JTextField();
        LabelEmailUser2 = new javax.swing.JLabel();
        textEditPetRaca = new javax.swing.JTextField();
        LabelSenhaUser3 = new javax.swing.JLabel();
        textEditPetCor = new javax.swing.JTextField();
        BtnCancelCadAnimal = new javax.swing.JButton();
        LabelNomeUser5 = new javax.swing.JLabel();
        LabelSenhaUser4 = new javax.swing.JLabel();
        cbxEditSituacao = new javax.swing.JComboBox<>();
        BtnEditPet = new javax.swing.JButton();
        LabelNomeUser7 = new javax.swing.JLabel();
        txtEditIdPet = new javax.swing.JTextField();
        BtnExcluirCadAnimal = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        textEditDetal = new javax.swing.JTextArea();

        btnEditarPet1.setBackground(new java.awt.Color(161, 236, 242));
        btnEditarPet1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarPet1.setText("Editar");
        btnEditarPet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPet1MouseClicked(evt);
            }
        });
        btnEditarPet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPet1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        PanelMenus.setBackground(new java.awt.Color(161, 236, 242));
        PanelMenus.setLayout(null);

        LabelMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelMenu.setForeground(new java.awt.Color(59, 61, 75));
        LabelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mask.png"))); // NOI18N
        PanelMenus.add(LabelMenu);
        LabelMenu.setBounds(0, 20, 150, 110);

        MenuPerdidos.setBackground(new java.awt.Color(255, 255, 255));
        MenuPerdidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuPerdidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuPerdidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPerdidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuPerdidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuPerdidosMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(59, 61, 75));
        jLabel2.setText(" Perdidos");

        javax.swing.GroupLayout MenuPerdidosLayout = new javax.swing.GroupLayout(MenuPerdidos);
        MenuPerdidos.setLayout(MenuPerdidosLayout);
        MenuPerdidosLayout.setHorizontalGroup(
            MenuPerdidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        MenuPerdidosLayout.setVerticalGroup(
            MenuPerdidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        PanelMenus.add(MenuPerdidos);
        MenuPerdidos.setBounds(10, 140, 140, 50);

        MenuAchados.setBackground(new java.awt.Color(255, 255, 255));
        MenuAchados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuAchados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuAchados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAchadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuAchadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuAchadosMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(59, 61, 75));
        jLabel3.setText(" Achados");

        javax.swing.GroupLayout MenuAchadosLayout = new javax.swing.GroupLayout(MenuAchados);
        MenuAchados.setLayout(MenuAchadosLayout);
        MenuAchadosLayout.setHorizontalGroup(
            MenuAchadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        MenuAchadosLayout.setVerticalGroup(
            MenuAchadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        PanelMenus.add(MenuAchados);
        MenuAchados.setBounds(10, 210, 140, 50);

        MenuCadastros.setBackground(new java.awt.Color(255, 255, 255));
        MenuCadastros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCadastrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuCadastrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuCadastrosMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(59, 61, 75));
        jLabel4.setText(" Cadastros");

        javax.swing.GroupLayout MenuCadastrosLayout = new javax.swing.GroupLayout(MenuCadastros);
        MenuCadastros.setLayout(MenuCadastrosLayout);
        MenuCadastrosLayout.setHorizontalGroup(
            MenuCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        MenuCadastrosLayout.setVerticalGroup(
            MenuCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        PanelMenus.add(MenuCadastros);
        MenuCadastros.setBounds(10, 280, 140, 50);

        MenuUsers.setBackground(new java.awt.Color(255, 255, 255));
        MenuUsers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuUsersMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(59, 61, 75));
        jLabel9.setText("Perfil");

        javax.swing.GroupLayout MenuUsersLayout = new javax.swing.GroupLayout(MenuUsers);
        MenuUsers.setLayout(MenuUsersLayout);
        MenuUsersLayout.setHorizontalGroup(
            MenuUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        MenuUsersLayout.setVerticalGroup(
            MenuUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        PanelMenus.add(MenuUsers);
        MenuUsers.setBounds(10, 350, 140, 50);

        MenuCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        MenuCadastrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuCadastrarMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(59, 61, 75));
        jLabel5.setText(" Cadastrar pet");

        javax.swing.GroupLayout MenuCadastrarLayout = new javax.swing.GroupLayout(MenuCadastrar);
        MenuCadastrar.setLayout(MenuCadastrarLayout);
        MenuCadastrarLayout.setHorizontalGroup(
            MenuCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        MenuCadastrarLayout.setVerticalGroup(
            MenuCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        PanelMenus.add(MenuCadastrar);
        MenuCadastrar.setBounds(10, 420, 140, 50);

        LabelSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelSair.setText(" Sair");
        LabelSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelSairMouseClicked(evt);
            }
        });
        PanelMenus.add(LabelSair);
        LabelSair.setBounds(10, 480, 37, 16);

        getContentPane().add(PanelMenus);
        PanelMenus.setBounds(0, 0, 150, 500);

        PanelPrincipal.setBackground(new java.awt.Color(161, 236, 242));
        PanelPrincipal.setLayout(null);

        PanelPerdidos.setBackground(new java.awt.Color(255, 255, 255));
        PanelPerdidos.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(59, 61, 75)));
        PanelPerdidos.setLayout(null);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDescriçãoPerdidos.setEditable(false);
        txtDescriçãoPerdidos.setColumns(20);
        txtDescriçãoPerdidos.setLineWrap(true);
        txtDescriçãoPerdidos.setRows(5);
        jScrollPane5.setViewportView(txtDescriçãoPerdidos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        PanelPerdidos.add(jPanel1);
        jPanel1.setBounds(400, 20, 210, 420);

        TableAnimaisPerdidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Espécie", "Raça", "Cor", "Descrição", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableAnimaisPerdidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAnimaisPerdidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableAnimaisPerdidos);
        if (TableAnimaisPerdidos.getColumnModel().getColumnCount() > 0) {
            TableAnimaisPerdidos.getColumnModel().getColumn(0).setResizable(false);
            TableAnimaisPerdidos.getColumnModel().getColumn(0).setPreferredWidth(30);
            TableAnimaisPerdidos.getColumnModel().getColumn(5).setResizable(false);
            TableAnimaisPerdidos.getColumnModel().getColumn(5).setPreferredWidth(0);
            TableAnimaisPerdidos.getColumnModel().getColumn(6).setResizable(false);
            TableAnimaisPerdidos.getColumnModel().getColumn(6).setPreferredWidth(0);
        }

        PanelPerdidos.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 370, 420);

        PanelPrincipal.add(PanelPerdidos);
        PanelPerdidos.setBounds(10, 15, 630, 470);

        PanelAchados.setBackground(new java.awt.Color(255, 255, 255));
        PanelAchados.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(59, 61, 75)));
        PanelAchados.setLayout(null);

        TableAnimaisAchados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Espécie", "Raça", "Cor", "Descrição", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableAnimaisAchados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAnimaisAchadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableAnimaisAchados);
        if (TableAnimaisAchados.getColumnModel().getColumnCount() > 0) {
            TableAnimaisAchados.getColumnModel().getColumn(0).setResizable(false);
            TableAnimaisAchados.getColumnModel().getColumn(0).setPreferredWidth(30);
            TableAnimaisAchados.getColumnModel().getColumn(5).setResizable(false);
            TableAnimaisAchados.getColumnModel().getColumn(5).setPreferredWidth(0);
            TableAnimaisAchados.getColumnModel().getColumn(6).setResizable(false);
            TableAnimaisAchados.getColumnModel().getColumn(6).setPreferredWidth(0);
        }

        PanelAchados.add(jScrollPane2);
        jScrollPane2.setBounds(20, 20, 370, 420);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDescriçãoAchados.setColumns(20);
        txtDescriçãoAchados.setLineWrap(true);
        txtDescriçãoAchados.setRows(5);
        jScrollPane8.setViewportView(txtDescriçãoAchados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        PanelAchados.add(jPanel2);
        jPanel2.setBounds(400, 20, 210, 420);

        PanelPrincipal.add(PanelAchados);
        PanelAchados.setBounds(10, 15, 630, 470);

        PanelCadastros.setBackground(new java.awt.Color(255, 255, 255));
        PanelCadastros.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(59, 61, 75)));
        PanelCadastros.setLayout(null);

        TableCadastros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Espécie", "Raça", "Cor", "Descrição", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCadastrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableCadastros);
        if (TableCadastros.getColumnModel().getColumnCount() > 0) {
            TableCadastros.getColumnModel().getColumn(0).setPreferredWidth(30);
            TableCadastros.getColumnModel().getColumn(4).setResizable(false);
            TableCadastros.getColumnModel().getColumn(5).setResizable(false);
            TableCadastros.getColumnModel().getColumn(5).setPreferredWidth(0);
        }

        PanelCadastros.add(jScrollPane3);
        jScrollPane3.setBounds(20, 20, 370, 420);

        btnEditarPet.setBackground(new java.awt.Color(161, 236, 242));
        btnEditarPet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarPet.setText("Editar");
        btnEditarPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPetMouseClicked(evt);
            }
        });

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDescriçãoCadastros.setEditable(false);
        txtDescriçãoCadastros.setColumns(20);
        txtDescriçãoCadastros.setLineWrap(true);
        txtDescriçãoCadastros.setRows(5);
        jScrollPane7.setViewportView(txtDescriçãoCadastros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(btnEditarPet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarPet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCadastros.add(jPanel3);
        jPanel3.setBounds(400, 20, 210, 420);

        PanelPrincipal.add(PanelCadastros);
        PanelCadastros.setBounds(10, 15, 630, 470);

        PanelPerfil.setBackground(new java.awt.Color(255, 255, 255));
        PanelPerfil.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(59, 61, 75)));
        PanelPerfil.setLayout(null);

        PanelEditarUser1.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditarUser1.setLayout(null);

        txtEditNome1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        txtEditNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditNome1ActionPerformed(evt);
            }
        });
        PanelEditarUser1.add(txtEditNome1);
        txtEditNome1.setBounds(60, 120, 430, 30);

        LabelNomeUser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNomeUser1.setText("Nome");
        PanelEditarUser1.add(LabelNomeUser1);
        LabelNomeUser1.setBounds(60, 100, 290, 20);

        textEditTel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        textEditTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditTel1ActionPerformed(evt);
            }
        });
        PanelEditarUser1.add(textEditTel1);
        textEditTel1.setBounds(60, 250, 430, 30);

        LabelTelefoneUser3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTelefoneUser3.setText("Telefone");
        PanelEditarUser1.add(LabelTelefoneUser3);
        LabelTelefoneUser3.setBounds(60, 230, 290, 20);

        textEditEmail1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        textEditEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditEmail1ActionPerformed(evt);
            }
        });
        PanelEditarUser1.add(textEditEmail1);
        textEditEmail1.setBounds(60, 190, 430, 30);

        LabelEmailUser3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelEmailUser3.setText("Email");
        PanelEditarUser1.add(LabelEmailUser3);
        LabelEmailUser3.setBounds(60, 170, 290, 20);

        BtnSalvarEditUser1.setBackground(new java.awt.Color(161, 236, 242));
        BtnSalvarEditUser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSalvarEditUser1.setText("Salvar");
        BtnSalvarEditUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalvarEditUser1MouseClicked(evt);
            }
        });
        BtnSalvarEditUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarEditUser1ActionPerformed(evt);
            }
        });
        PanelEditarUser1.add(BtnSalvarEditUser1);
        BtnSalvarEditUser1.setBounds(460, 370, 110, 40);

        txtEditId1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        txtEditId1.setEnabled(false);
        txtEditId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditId1ActionPerformed(evt);
            }
        });
        PanelEditarUser1.add(txtEditId1);
        txtEditId1.setBounds(80, 50, 120, 30);

        LabelNomeUser8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNomeUser8.setText("Id");
        PanelEditarUser1.add(LabelNomeUser8);
        LabelNomeUser8.setBounds(60, 60, 290, 20);

        LabelTelefoneUser4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTelefoneUser4.setText("Senha");
        PanelEditarUser1.add(LabelTelefoneUser4);
        LabelTelefoneUser4.setBounds(60, 310, 290, 20);

        textEditPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        textEditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditPassActionPerformed(evt);
            }
        });
        PanelEditarUser1.add(textEditPass);
        textEditPass.setBounds(60, 330, 430, 30);

        PanelPerfil.add(PanelEditarUser1);
        PanelEditarUser1.setBounds(10, 10, 610, 450);

        PanelPrincipal.add(PanelPerfil);
        PanelPerfil.setBounds(10, 15, 630, 470);

        PanelCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        PanelCadastrar.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(59, 61, 75)));
        PanelCadastrar.setLayout(null);

        LabelTelefoneUser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTelefoneUser1.setText("Espécie");
        PanelCadastrar.add(LabelTelefoneUser1);
        LabelTelefoneUser1.setBounds(30, 110, 160, 20);

        TxtCadPetEspecie.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        TxtCadPetEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadPetEspecieActionPerformed(evt);
            }
        });
        PanelCadastrar.add(TxtCadPetEspecie);
        TxtCadPetEspecie.setBounds(30, 130, 300, 30);

        LabelEmailUser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelEmailUser1.setText("Raça");
        PanelCadastrar.add(LabelEmailUser1);
        LabelEmailUser1.setBounds(30, 190, 160, 20);

        TxtCadPetRaca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        TxtCadPetRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadPetRacaActionPerformed(evt);
            }
        });
        PanelCadastrar.add(TxtCadPetRaca);
        TxtCadPetRaca.setBounds(30, 210, 300, 30);

        LabelSenhaUser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSenhaUser1.setText("Situação");
        PanelCadastrar.add(LabelSenhaUser1);
        LabelSenhaUser1.setBounds(30, 350, 160, 20);

        TxtCadPetCor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        TxtCadPetCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadPetCorActionPerformed(evt);
            }
        });
        PanelCadastrar.add(TxtCadPetCor);
        TxtCadPetCor.setBounds(30, 290, 300, 30);

        BtnSalvarCadastroPet.setBackground(new java.awt.Color(161, 236, 242));
        BtnSalvarCadastroPet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSalvarCadastroPet.setText("Salvar");
        BtnSalvarCadastroPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalvarCadastroPetMouseClicked(evt);
            }
        });
        BtnSalvarCadastroPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarCadastroPetActionPerformed(evt);
            }
        });
        PanelCadastrar.add(BtnSalvarCadastroPet);
        BtnSalvarCadastroPet.setBounds(460, 400, 110, 40);

        LabelNomeUser2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNomeUser2.setText("Detalhes");
        PanelCadastrar.add(LabelNomeUser2);
        LabelNomeUser2.setBounds(360, 20, 110, 20);

        LabelSenhaUser2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSenhaUser2.setText("Cor");
        PanelCadastrar.add(LabelSenhaUser2);
        LabelSenhaUser2.setBounds(30, 270, 160, 20);

        cbxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSituacaoActionPerformed(evt);
            }
        });
        PanelCadastrar.add(cbxSituacao);
        cbxSituacao.setBounds(30, 380, 140, 22);

        LabelNomeUser6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNomeUser6.setText("Nome");
        PanelCadastrar.add(LabelNomeUser6);
        LabelNomeUser6.setBounds(30, 30, 160, 20);

        TxtCadPetNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        TxtCadPetNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadPetNomeActionPerformed(evt);
            }
        });
        PanelCadastrar.add(TxtCadPetNome);
        TxtCadPetNome.setBounds(30, 50, 300, 30);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TxtCadPetDetalhes.setColumns(20);
        TxtCadPetDetalhes.setLineWrap(true);
        TxtCadPetDetalhes.setRows(5);
        jScrollPane6.setViewportView(TxtCadPetDetalhes);

        PanelCadastrar.add(jScrollPane6);
        jScrollPane6.setBounds(360, 50, 250, 330);

        PanelPrincipal.add(PanelCadastrar);
        PanelCadastrar.setBounds(10, 15, 630, 470);

        getContentPane().add(PanelPrincipal);
        PanelPrincipal.setBounds(150, 0, 650, 500);

        PanelEditarPet.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditarPet.setLayout(null);

        LabelNomeUser4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNomeUser4.setText("Nome");
        PanelEditarPet.add(LabelNomeUser4);
        LabelNomeUser4.setBounds(50, 60, 160, 20);

        textEditPetNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        textEditPetNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditPetNomeActionPerformed(evt);
            }
        });
        PanelEditarPet.add(textEditPetNome);
        textEditPetNome.setBounds(50, 80, 300, 30);

        LabelTelefoneUser2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTelefoneUser2.setText("Espécie");
        PanelEditarPet.add(LabelTelefoneUser2);
        LabelTelefoneUser2.setBounds(50, 140, 160, 20);

        textEditPetEspecie.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        textEditPetEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditPetEspecieActionPerformed(evt);
            }
        });
        PanelEditarPet.add(textEditPetEspecie);
        textEditPetEspecie.setBounds(50, 160, 300, 30);

        LabelEmailUser2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelEmailUser2.setText("Raça");
        PanelEditarPet.add(LabelEmailUser2);
        LabelEmailUser2.setBounds(50, 220, 160, 20);

        textEditPetRaca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        textEditPetRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditPetRacaActionPerformed(evt);
            }
        });
        PanelEditarPet.add(textEditPetRaca);
        textEditPetRaca.setBounds(50, 240, 300, 30);

        LabelSenhaUser3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSenhaUser3.setText("Situação");
        PanelEditarPet.add(LabelSenhaUser3);
        LabelSenhaUser3.setBounds(50, 380, 160, 20);

        textEditPetCor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        textEditPetCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditPetCorActionPerformed(evt);
            }
        });
        PanelEditarPet.add(textEditPetCor);
        textEditPetCor.setBounds(50, 320, 300, 30);

        BtnCancelCadAnimal.setBackground(new java.awt.Color(161, 236, 242));
        BtnCancelCadAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCancelCadAnimal.setText("Cancelar");
        BtnCancelCadAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelCadAnimalMouseClicked(evt);
            }
        });
        BtnCancelCadAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelCadAnimalActionPerformed(evt);
            }
        });
        PanelEditarPet.add(BtnCancelCadAnimal);
        BtnCancelCadAnimal.setBounds(560, 400, 110, 40);

        LabelNomeUser5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNomeUser5.setText("Detalhes");
        PanelEditarPet.add(LabelNomeUser5);
        LabelNomeUser5.setBounds(420, 20, 110, 20);

        LabelSenhaUser4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSenhaUser4.setText("Cor");
        PanelEditarPet.add(LabelSenhaUser4);
        LabelSenhaUser4.setBounds(50, 300, 160, 20);

        cbxEditSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxEditSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEditSituacaoActionPerformed(evt);
            }
        });
        PanelEditarPet.add(cbxEditSituacao);
        cbxEditSituacao.setBounds(50, 410, 160, 40);

        BtnEditPet.setBackground(new java.awt.Color(161, 236, 242));
        BtnEditPet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEditPet.setText("Salvar");
        BtnEditPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditPetMouseClicked(evt);
            }
        });
        BtnEditPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditPetActionPerformed(evt);
            }
        });
        PanelEditarPet.add(BtnEditPet);
        BtnEditPet.setBounds(440, 400, 110, 40);

        LabelNomeUser7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNomeUser7.setText("Id");
        PanelEditarPet.add(LabelNomeUser7);
        LabelNomeUser7.setBounds(60, 30, 20, 20);

        txtEditIdPet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 61, 75)));
        txtEditIdPet.setEnabled(false);
        txtEditIdPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditIdPetActionPerformed(evt);
            }
        });
        PanelEditarPet.add(txtEditIdPet);
        txtEditIdPet.setBounds(80, 20, 90, 30);

        BtnExcluirCadAnimal.setBackground(new java.awt.Color(161, 236, 242));
        BtnExcluirCadAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnExcluirCadAnimal.setText("Excluir");
        BtnExcluirCadAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExcluirCadAnimalMouseClicked(evt);
            }
        });
        BtnExcluirCadAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirCadAnimalActionPerformed(evt);
            }
        });
        PanelEditarPet.add(BtnExcluirCadAnimal);
        BtnExcluirCadAnimal.setBounds(680, 400, 110, 40);

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setToolTipText("");

        textEditDetal.setColumns(20);
        textEditDetal.setLineWrap(true);
        textEditDetal.setRows(5);
        jScrollPane9.setViewportView(textEditDetal);

        PanelEditarPet.add(jScrollPane9);
        jScrollPane9.setBounds(420, 50, 370, 330);

        getContentPane().add(PanelEditarPet);
        PanelEditarPet.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    /*private carregar_pets_grid () {
    
    ConectarDao c1 = new ConectarDao(); 
    
    
    String sql = "Select * from adm, usuarios where adm.cod = usuarios.cod";
    
   try {
        
       
               
   
   }
   catch( SQLException err )

}*/

    private void MenuPerdidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPerdidosMouseEntered
        // TODO add your handling code here:
        this.MenuPerdidos.setBackground(new java.awt.Color(86, 169, 176));
    }//GEN-LAST:event_MenuPerdidosMouseEntered

    private void MenuPerdidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPerdidosMouseExited
        // TODO add your handling code here:
        this.MenuPerdidos.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_MenuPerdidosMouseExited

    private void MenuAchadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAchadosMouseEntered
        // TODO add your handling code here:
        this.MenuAchados.setBackground(new java.awt.Color(86, 169, 176));
    }//GEN-LAST:event_MenuAchadosMouseEntered

    private void MenuAchadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAchadosMouseExited
        // TODO add your handling code here:
        this.MenuAchados.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_MenuAchadosMouseExited

    private void MenuCadastrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastrosMouseEntered
        // TODO add your handling code here:
        this.MenuCadastros.setBackground(new java.awt.Color(86, 169, 176));
    }//GEN-LAST:event_MenuCadastrosMouseEntered

    private void MenuCadastrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastrosMouseExited
        // TODO add your handling code here:
        this.MenuCadastros.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_MenuCadastrosMouseExited

    private void MenuCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastrarMouseEntered
        // TODO add your handling code here:
        this.MenuCadastrar.setBackground(new java.awt.Color(86, 169, 176));
    }//GEN-LAST:event_MenuCadastrarMouseEntered

    private void MenuCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastrarMouseExited
        // TODO add your handling code here:
        this.MenuCadastrar.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_MenuCadastrarMouseExited

    private void MenuPerdidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPerdidosMouseClicked
        // TODO add your handling code here:
        this.PanelAchados.setVisible(false);
        this.PanelPerfil.setVisible(false);
        this.PanelCadastros.setVisible(false);
        this.PanelPerdidos.setVisible(true);
        this.PanelCadastrar.setVisible(false);
        ListarValoresPetPerdidos();
    }//GEN-LAST:event_MenuPerdidosMouseClicked

    private void MenuAchadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAchadosMouseClicked
        // TODO add your handling code here:
        ListarValoresPetEncontrados();
        ListarValoresPetPerdidos();

        this.PanelAchados.setVisible(true);
        this.PanelPerfil.setVisible(false);
        this.PanelCadastros.setVisible(false);
        this.PanelPerdidos.setVisible(false);
        this.PanelCadastrar.setVisible(false);
        ListarValoresPetEncontrados();
    }//GEN-LAST:event_MenuAchadosMouseClicked

    private void MenuCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastrosMouseClicked
        // TODO add your handling code here:
        this.PanelAchados.setVisible(false);
        this.PanelPerfil.setVisible(false);
        this.PanelCadastros.setVisible(true);
        this.PanelPerdidos.setVisible(false);
        this.PanelCadastrar.setVisible(false);
        ListarValoresPet();
    }//GEN-LAST:event_MenuCadastrosMouseClicked

    private void MenuCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastrarMouseClicked
        // TODO add your handling code here:
        this.PanelAchados.setVisible(false);
        this.PanelPerfil.setVisible(false);
        this.PanelCadastros.setVisible(false);
        this.PanelPerdidos.setVisible(false);
        this.PanelCadastrar.setVisible(true);
    }//GEN-LAST:event_MenuCadastrarMouseClicked

    private void MenuUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUsersMouseClicked
        // TODO add your handling code here:
        this.PanelAchados.setVisible(false);
        this.PanelPerfil.setVisible(true);
        this.PanelCadastros.setVisible(false);
        this.PanelPerdidos.setVisible(false);
        this.PanelCadastrar.setVisible(false);
    }//GEN-LAST:event_MenuUsersMouseClicked

    private void MenuUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUsersMouseEntered
        // TODO add your handling code here:
        this.MenuUsers.setBackground(new java.awt.Color(86, 169, 176));
    }//GEN-LAST:event_MenuUsersMouseEntered

    private void MenuUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUsersMouseExited
        // TODO add your handling code here:
        this.MenuUsers.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_MenuUsersMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ListarValoresPetPerdidos();

        this.PanelAchados.setVisible(false);
        this.PanelPerfil.setVisible(false);
        this.PanelCadastros.setVisible(false);
        this.PanelPerdidos.setVisible(true);
        this.PanelCadastrar.setVisible(false);
        this.PanelEditarPet.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void LabelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSairMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LabelSairMouseClicked

    private void TableAnimaisPerdidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAnimaisPerdidosMouseClicked
        // TODO add your handling code here:
        

        int setar = TableAnimaisPerdidos.getSelectedRow();
        int idpet = (int) TableAnimaisPerdidos.getModel().getValueAt(setar, 0);
        int iduser = 0;
        
        String telefone = "sem informação", nome="sem informação";
        
        Animal objpet = new Animal();
        objpet.setPet_id(idpet);
        
        Petdao objpetdao = new Petdao();
        ResultSet rspetdao = objpetdao.pesquisarId(objpet);
        
        try {
            if(rspetdao.next()){
                iduser = rspetdao.getInt("fk_id_user");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicioUSER.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        User objuser = new User();
        objuser.setId(iduser);
        
        Usuariodao objuserdao = new Usuariodao();
        ResultSet rsuserdao = objuserdao.pesquisarId(objuser);
        
        try {
            if(rsuserdao.next()){
                telefone = rsuserdao.getString("user_telefone");
                nome = rsuserdao.getString("user_nome");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicioUSER.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtDescriçãoPerdidos.setText("Nome: " + TableAnimaisPerdidos.getModel().getValueAt(setar, 1).toString() + "\n"
                + "\nEspécie: " + TableAnimaisPerdidos.getModel().getValueAt(setar, 2).toString() + "\n"
                + "\nRaça: " + TableAnimaisPerdidos.getModel().getValueAt(setar, 3).toString() + "\n"
                + "\nCor: " + TableAnimaisPerdidos.getModel().getValueAt(setar, 4).toString() + "\n"
                + "\nDescrição: " + TableAnimaisPerdidos.getModel().getValueAt(setar, 5).toString() +"\n"
                + "\nNome de quem perdeu: " + nome + "\n"
                + "\nContato: " + telefone + "\n"
        );
    }//GEN-LAST:event_TableAnimaisPerdidosMouseClicked

    private void TableAnimaisAchadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAnimaisAchadosMouseClicked
        // TODO add your handling code here:
        int setar = TableAnimaisAchados.getSelectedRow();
        
        int idpet = (int) TableAnimaisAchados.getModel().getValueAt(setar, 0);
        int iduser = 0;
        
        String telefone = "sem informação", nome="sem informação";
        
        Animal objpet = new Animal();
        objpet.setPet_id(idpet);
        
        Petdao objpetdao = new Petdao();
        ResultSet rspetdao = objpetdao.pesquisarId(objpet);
        
        try {
            if(rspetdao.next()){
                iduser = rspetdao.getInt("fk_id_user");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicioUSER.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        User objuser = new User();
        objuser.setId(iduser);
        
        Usuariodao objuserdao = new Usuariodao();
        ResultSet rsuserdao = objuserdao.pesquisarId(objuser);
        
        try {
            if(rsuserdao.next()){
                telefone = rsuserdao.getString("user_telefone");
                nome = rsuserdao.getString("user_nome");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicioUSER.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtDescriçãoAchados.setText("Nome: " + TableAnimaisAchados.getModel().getValueAt(setar, 1).toString() + "\n"
                + "\nEspécie: " + TableAnimaisAchados.getModel().getValueAt(setar, 2).toString() + "\n"
                + "\nRaça: " + TableAnimaisAchados.getModel().getValueAt(setar, 3).toString() + "\n"
                + "\nCor: " + TableAnimaisAchados.getModel().getValueAt(setar, 4).toString() + "\n"
                + "\nDescrição: " + TableAnimaisAchados.getModel().getValueAt(setar, 5).toString() + "\n"
                + "\nNome de quem achou: " + nome + "\n"
                + "\nContato: " + telefone + "\n"
        );
    }//GEN-LAST:event_TableAnimaisAchadosMouseClicked

    private void TableCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCadastrosMouseClicked
        // TODO add your handling code here:
        int setar = TableCadastros.getSelectedRow();

        txtDescriçãoCadastros.setText("Nome: " + TableCadastros.getModel().getValueAt(setar, 1).toString() + "\n"
                + "\nEspécie: " + TableCadastros.getModel().getValueAt(setar, 2).toString() + "\n"
                + "\nRaça: " + TableCadastros.getModel().getValueAt(setar, 3).toString() + "\n"
                + "\nCor: " + TableCadastros.getModel().getValueAt(setar, 4).toString() + "\n"
                + "\nSituação: " + TableCadastros.getModel().getValueAt(setar, 6).toString() + "\n"
                + "\nDescrição: " + TableCadastros.getModel().getValueAt(setar, 5).toString());
    }//GEN-LAST:event_TableCadastrosMouseClicked

    private void TxtCadPetEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadPetEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadPetEspecieActionPerformed

    private void TxtCadPetRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadPetRacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadPetRacaActionPerformed

    private void TxtCadPetCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadPetCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadPetCorActionPerformed

    private void BtnSalvarCadastroPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarCadastroPetActionPerformed
        // TODO add your handling code here:
        String pet_nome, pet_especie, pet_raca, pet_cor, pet_detalhes;
        int codsit, fk_id_user;

        pet_nome = TxtCadPetNome.getText();
        pet_especie = TxtCadPetEspecie.getText();
        pet_raca = TxtCadPetRaca.getText();
        pet_cor = TxtCadPetCor.getText();
        pet_detalhes = TxtCadPetDetalhes.getText();
        codsit = id_situacao.get(cbxSituacao.getSelectedIndex() - 1);
        fk_id_user = id_user;

        Animal objpet = new Animal();
        objpet.setPet_nome(pet_nome);
        objpet.setPet_especie(pet_especie);
        objpet.setPet_raca(pet_raca);
        objpet.setPet_cor(pet_cor);
        objpet.setPet_detalhes(pet_detalhes);
        objpet.setPet_sit(codsit);
        objpet.setFk_id_user(fk_id_user);

        Petdao objpetdao = new Petdao();
        objpetdao.cadastrarPet(objpet);
    }//GEN-LAST:event_BtnSalvarCadastroPetActionPerformed

    private void BtnSalvarCadastroPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalvarCadastroPetMouseClicked
        // TODO add your handling code here:
        ListarValoresPet();

        this.PanelAchados.setVisible(false);
        this.PanelPerfil.setVisible(false);
        this.PanelCadastros.setVisible(false);
        this.PanelPerdidos.setVisible(false);
        this.PanelCadastrar.setVisible(true);
        this.PanelEditarPet.setVisible(false);

        JOptionPane.showMessageDialog(null, "Cadastro realizado!");
        LimparCamposCadastrarPet();


    }//GEN-LAST:event_BtnSalvarCadastroPetMouseClicked

    private void textEditPetNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditPetNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditPetNomeActionPerformed

    private void textEditPetEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditPetEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditPetEspecieActionPerformed

    private void textEditPetRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditPetRacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditPetRacaActionPerformed

    private void textEditPetCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditPetCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditPetCorActionPerformed

    private void BtnCancelCadAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelCadAnimalMouseClicked
        // TODO add your handling code here:

        this.PanelEditarPet.setVisible(false);
        this.PanelPrincipal.setVisible(true);
        this.PanelMenus.setVisible(true);
        this.PanelCadastros.setVisible(true);
    }//GEN-LAST:event_BtnCancelCadAnimalMouseClicked

    private void BtnCancelCadAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelCadAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelCadAnimalActionPerformed

    private void BtnEditPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditPetMouseClicked
        // TODO add your handling code here:

        this.PanelEditarPet.setVisible(false);
        this.PanelPrincipal.setVisible(true);
        this.PanelMenus.setVisible(true);
        this.PanelCadastros.setVisible(true);
    }//GEN-LAST:event_BtnEditPetMouseClicked

    private void BtnEditPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditPetActionPerformed
        // TODO add your handling code here:

        AlterarPet();
        ListarValoresPet();
        LimparCamposEditPet();


    }//GEN-LAST:event_BtnEditPetActionPerformed

    private void btnEditarPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPetMouseClicked
        // TODO add your handling code here:
        this.PanelEditarPet.setVisible(true);
        this.PanelMenus.setVisible(false);
        this.PanelPrincipal.setVisible(false);

        int setar = TableCadastros.getSelectedRow();
        // TelaEditarUser objedituser = new TelaEditarUser();

        txtEditIdPet.setText(TableCadastros.getModel().getValueAt(setar, 0).toString());
        textEditPetNome.setText(TableCadastros.getModel().getValueAt(setar, 1).toString());
        textEditPetEspecie.setText(TableCadastros.getModel().getValueAt(setar, 2).toString());
        textEditPetRaca.setText(TableCadastros.getModel().getValueAt(setar, 3).toString());
        textEditPetCor.setText(TableCadastros.getModel().getValueAt(setar, 4).toString());
        textEditDetal.setText(TableCadastros.getModel().getValueAt(setar, 5).toString());
    }//GEN-LAST:event_btnEditarPetMouseClicked

    private void TxtCadPetNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadPetNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadPetNomeActionPerformed

    private void txtEditIdPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditIdPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditIdPetActionPerformed

    private void btnEditarPet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPet1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarPet1MouseClicked

    private void btnEditarPet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarPet1ActionPerformed

    private void BtnExcluirCadAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExcluirCadAnimalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnExcluirCadAnimalMouseClicked

    private void BtnExcluirCadAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirCadAnimalActionPerformed
        // TODO add your handling code here:
        ExcluirPet();
        ListarValoresPet();
        LimparCamposEditPet();
    }//GEN-LAST:event_BtnExcluirCadAnimalActionPerformed

    private void cbxEditSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEditSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEditSituacaoActionPerformed

    private void cbxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSituacaoActionPerformed

    private void txtEditNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditNome1ActionPerformed

    private void textEditTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditTel1ActionPerformed

    private void textEditEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditEmail1ActionPerformed

    private void BtnSalvarEditUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalvarEditUser1MouseClicked
        // TODO add your handling code here:
        AlterarUsuario();
    }//GEN-LAST:event_BtnSalvarEditUser1MouseClicked

    private void BtnSalvarEditUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarEditUser1ActionPerformed
        // TODO add your handling code here:
        AlterarUsuario();
    }//GEN-LAST:event_BtnSalvarEditUser1ActionPerformed

    private void txtEditId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditId1ActionPerformed

    private void textEditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicioUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicioUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicioUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicioUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicioUSER(id_user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelCadAnimal;
    private javax.swing.JButton BtnEditPet;
    private javax.swing.JButton BtnExcluirCadAnimal;
    private javax.swing.JButton BtnSalvarCadastroPet;
    private javax.swing.JButton BtnSalvarEditUser1;
    private javax.swing.JLabel LabelEmailUser1;
    private javax.swing.JLabel LabelEmailUser2;
    private javax.swing.JLabel LabelEmailUser3;
    private javax.swing.JLabel LabelMenu;
    private javax.swing.JLabel LabelNomeUser1;
    private javax.swing.JLabel LabelNomeUser2;
    private javax.swing.JLabel LabelNomeUser4;
    private javax.swing.JLabel LabelNomeUser5;
    private javax.swing.JLabel LabelNomeUser6;
    private javax.swing.JLabel LabelNomeUser7;
    private javax.swing.JLabel LabelNomeUser8;
    private javax.swing.JLabel LabelSair;
    private javax.swing.JLabel LabelSenhaUser1;
    private javax.swing.JLabel LabelSenhaUser2;
    private javax.swing.JLabel LabelSenhaUser3;
    private javax.swing.JLabel LabelSenhaUser4;
    private javax.swing.JLabel LabelTelefoneUser1;
    private javax.swing.JLabel LabelTelefoneUser2;
    private javax.swing.JLabel LabelTelefoneUser3;
    private javax.swing.JLabel LabelTelefoneUser4;
    private javax.swing.JPanel MenuAchados;
    private javax.swing.JPanel MenuCadastrar;
    private javax.swing.JPanel MenuCadastros;
    private javax.swing.JPanel MenuPerdidos;
    private javax.swing.JPanel MenuUsers;
    private javax.swing.JPanel PanelAchados;
    private javax.swing.JPanel PanelCadastrar;
    private javax.swing.JPanel PanelCadastros;
    private javax.swing.JPanel PanelEditarPet;
    private javax.swing.JPanel PanelEditarUser1;
    private javax.swing.JPanel PanelMenus;
    private javax.swing.JPanel PanelPerdidos;
    private javax.swing.JPanel PanelPerfil;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTable TableAnimaisAchados;
    private javax.swing.JTable TableAnimaisPerdidos;
    private javax.swing.JTable TableCadastros;
    private javax.swing.JTextField TxtCadPetCor;
    private javax.swing.JTextArea TxtCadPetDetalhes;
    private javax.swing.JTextField TxtCadPetEspecie;
    private javax.swing.JTextField TxtCadPetNome;
    private javax.swing.JTextField TxtCadPetRaca;
    private javax.swing.JButton btnEditarPet;
    private javax.swing.JButton btnEditarPet1;
    private javax.swing.JComboBox<String> cbxEditSituacao;
    private javax.swing.JComboBox<String> cbxSituacao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea textEditDetal;
    private javax.swing.JTextField textEditEmail1;
    private javax.swing.JTextField textEditPass;
    private javax.swing.JTextField textEditPetCor;
    private javax.swing.JTextField textEditPetEspecie;
    private javax.swing.JTextField textEditPetNome;
    private javax.swing.JTextField textEditPetRaca;
    private javax.swing.JTextField textEditTel1;
    private javax.swing.JTextArea txtDescriçãoAchados;
    private javax.swing.JTextArea txtDescriçãoCadastros;
    private javax.swing.JTextArea txtDescriçãoPerdidos;
    private javax.swing.JTextField txtEditId1;
    private javax.swing.JTextField txtEditIdPet;
    private javax.swing.JTextField txtEditNome1;
    // End of variables declaration//GEN-END:variables

    private void ListarValores() {
        try {
            this.txtEditId1.setText(String.valueOf(id_user));
            User objuser = new User();
        objuser.setId(id_user);
        
        Usuariodao objuserdao = new Usuariodao();
        ResultSet rsuserdao = objuserdao.pesquisarId(objuser);
       
            if(rsuserdao.next()){
             String telefone = rsuserdao.getString("user_telefone");
             String nome = rsuserdao.getString("user_nome");
             String email = rsuserdao.getString("user_email");
             
             this.txtEditNome1.setText(nome);
             this.textEditTel1.setText(telefone);
             this.textEditEmail1.setText(email);
            }


        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "TelaInicioADM - ListarValores: " + erro);
        }
    }

    // Vector<Integer> id_acesso = new Vector<Integer>();

    /* public void restaurarDadosComboBoxAcesso() {

        try {

            Usuariodao objuserdao = new Usuariodao();
            ResultSet rs = objuserdao.listarAcesso();

            while (rs.next()) {
                id_acesso.addElement(rs.getInt(1));
                cbxAcesso.addItem(rs.getString(2));
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "TelaInicioADM - Carregar Cargo" + erro);
        }
    }*/
    private void AlterarUsuario() {

        Usuariodao objuserdao = new Usuariodao();
        //this.txtEditId1.setText(String.valueOf(objuserdao.PesquisarUsuario().get(1).getId()));
        int id_usuario, acesso = 2;
        String nome, email, telefone, pass;

        id_usuario = Integer.parseInt(txtEditId1.getText());
        nome = txtEditNome1.getText();
        email = textEditEmail1.getText();
        telefone = textEditTel1.getText();
        pass = textEditPass.getText();
        //acesso = id_acesso.get(cbxAcesso.getSelectedIndex() - 1);

        User objuser = new User();

        objuser.setId(id_usuario);
        objuser.setNome(nome);
        objuser.setEmail(email);
        objuser.setTelefone(telefone);
        objuser.setCod_acesso(acesso);
        objuser.setPass(pass);

        objuserdao.alterarUsuario2(objuser);

    }

    /*private void LimparCamposEditUser() {
        txtEditNome.setText("");
        textEditTel.setText("");
        textEditEmail.setText("");
    }*/

 /*private void ExcluirUsuario() {
        int id_usuario;

        id_usuario = Integer.parseInt(txtEditId.getText());

        User objuser = new User();
        objuser.setId(id_usuario);

        Usuariodao objuserdao = new Usuariodao();
        objuserdao.excluirUsuario(objuser);

    }*/
    // --------------------------------------------------------------------------------------------
    // Parte do Pet
    private void ListarValoresPet() {
        try {
            Petdao objpetdao = new Petdao();

            DefaultTableModel model = (DefaultTableModel) TableCadastros.getModel();
            model.setNumRows(0);

            ArrayList<Animal> lista = objpetdao.PesquisarPet();

            for (int num = 0; num < lista.size(); num++) {
                if (lista.get(num).getFk_id_user() == id_user) {
                    String petSitStatus;
                    if (lista.get(num).getPet_sit() == 1) {
                        petSitStatus = "Encontrado";
                    } else if (lista.get(num).getPet_sit() == 2) {
                        petSitStatus = "Perdido";
                    } else {
                        petSitStatus = String.valueOf(lista.get(num).getPet_sit()); // Caso haja outros valores possíveis
                    }

                    model.addRow(new Object[]{
                        lista.get(num).getPet_id(),
                        lista.get(num).getPet_nome(),
                        lista.get(num).getPet_especie(),
                        lista.get(num).getPet_raca(),
                        lista.get(num).getPet_cor(),
                        lista.get(num).getPet_detalhes(),
                        petSitStatus
                    });
                }
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "TelaInicioADM - ListarValoresPet: " + erro);
        }
    }

    private void ListarValoresPetPerdidos() {
        try {
            Petdao objpetdao = new Petdao();

            DefaultTableModel model = (DefaultTableModel) this.TableAnimaisPerdidos.getModel();
            model.setNumRows(0);

            ArrayList<Animal> lista = objpetdao.PesquisarPetPerdido();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getPet_id(),
                    lista.get(num).getPet_nome(),
                    lista.get(num).getPet_especie(),
                    lista.get(num).getPet_raca(),
                    lista.get(num).getPet_cor(),
                    lista.get(num).getPet_detalhes(),
                    lista.get(num).getPet_sit()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "TelaInicioADM - ListarValoresPet: " + erro);
        }
    }

    private void ListarValoresPetEncontrados() {
        try {
            Petdao objpetdao = new Petdao();

            DefaultTableModel model = (DefaultTableModel) this.TableAnimaisAchados.getModel();
            model.setNumRows(0);

            ArrayList<Animal> lista = objpetdao.PesquisarPetEncontrado();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getPet_id(),
                    lista.get(num).getPet_nome(),
                    lista.get(num).getPet_especie(),
                    lista.get(num).getPet_raca(),
                    lista.get(num).getPet_cor(),
                    lista.get(num).getPet_detalhes(),
                    lista.get(num).getPet_sit()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "TelaInicioADM - ListarValoresPet: " + erro);
        }
    }

    Vector<Integer> id_situacao = new Vector<Integer>();

    public void restaurarDadosComboBoxSituacao() {

        try {

            Petdao objpetdao = new Petdao();
            ResultSet rs = objpetdao.listarSituacao();

            while (rs.next()) {
                id_situacao.addElement(rs.getInt(1));
                cbxSituacao.addItem(rs.getString(2));
                cbxEditSituacao.addItem(rs.getString(2));
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "TelaInicioADM - Carregar Situacao Pet: " + erro);
        }
    }

    private void AlterarPet() {
        int id_pet, cod_sit;
        String pet_nome, pet_especie, pet_raca, pet_cor, pet_detalhes;

        id_pet = Integer.parseInt(txtEditIdPet.getText());
        pet_nome = textEditPetNome.getText();
        pet_especie = textEditPetEspecie.getText();
        pet_raca = textEditPetRaca.getText();
        pet_cor = textEditPetCor.getText();
        pet_detalhes = textEditDetal.getText();
        cod_sit = id_situacao.get(cbxEditSituacao.getSelectedIndex() - 1);

        Animal objpet = new Animal();

        objpet.setPet_id(id_pet);
        objpet.setPet_nome(pet_nome);
        objpet.setPet_especie(pet_especie);
        objpet.setPet_raca(pet_raca);
        objpet.setPet_cor(pet_cor);
        objpet.setPet_detalhes(pet_detalhes);
        objpet.setPet_sit(cod_sit);

        Petdao objpetdao = new Petdao();

        objpetdao.alterarPet(objpet);

    }

    private void LimparCamposEditPet() {
        textEditPetNome.setText("");
        textEditPetEspecie.setText("");
        textEditPetRaca.setText("");
        textEditPetCor.setText("");
        textEditDetal.setText("");
    }

    private void LimparCamposCadastrarPet() {
        TxtCadPetNome.setText("");
        TxtCadPetEspecie.setText("");
        TxtCadPetRaca.setText("");
        TxtCadPetCor.setText("");
        TxtCadPetDetalhes.setText("");
    }

    private void ExcluirPet() {
        int id_pet;

        id_pet = Integer.parseInt(txtEditIdPet.getText());

        Animal objpet = new Animal();
        objpet.setPet_id(id_pet);

        Petdao objpetdao = new Petdao();
        objpetdao.excluirPet(objpet);
    }

}
